name: Metrics
on:
  # Update daily
  schedule: [{cron: "0 0 * * *"}]
  # Run manually
  workflow_dispatch:
  # Run on every push on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: skrylexx
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
